# Generated by Django 5.2 on 2025-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
