# Generated by Django 5.2 on 2025-05-04 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorystock_date_alter_inventorystock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystock',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
