# Generated by Django 5.2 on 2025-05-05 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
        ),
    ]
