# Generated by Django 5.2 on 2025-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
