# Generated by Django 5.2 on 2025-05-23 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorystock_id'),
        ('transaction', '0003_purchasebill_purchasebilldetails_purchaseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBill',
            fields=[
                ('bill_no', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('gstin', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleBillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eway', models.CharField(blank=True, max_length=50, null=True)),
                ('veh', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('po', models.CharField(blank=True, max_length=50, null=True)),
                ('cgst', models.CharField(blank=True, max_length=50, null=True)),
                ('sgst', models.CharField(blank=True, max_length=50, null=True)),
                ('igst', models.CharField(blank=True, max_length=50, null=True)),
                ('cess', models.CharField(blank=True, max_length=50, null=True)),
                ('tcs', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleBillDetail', to='transaction.salebill')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('per_price', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=1)),
                ('bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_bill', to='transaction.salebill')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_stock', to='inventory.inventorystock')),
            ],
        ),
    ]
